### ISSUE TITLE
bootstrap not processing zsh directory/symlinks

### ISSUE THREAD

**Issue by snesbittsea** [agross/dotfiles#3]
I'm probably doing something stupid, but running bootstrap from the .dotfiles directory does not seem to be processing the zsh directory - no symlinks are created.

This is under ubuntu cuttlefish and the latest from your dotfiles repo.

Any help would be much appreciated.

A bit more info:

- The last folder processed is git
- commenting out the set -euo pipefail allows all folders to be processed and my .zshrc links appear.

Seems like something is silently failing.

-steve

**Comment by agross** [comment]
If you're running this from a non-Cygwin shell the symlinks [are omitted](https://github.com/agross/dotfiles/blob/master/zsh/bootstrap#L17). This is useful for me because I run Cygwin zsh, but not MinGW zsh (not sure this package even exists) and having `.zshrc` in `%USERPROFILE%` does not make sense in this case.

If you think this is not related to Windows/Cygwin/Msys/MinGW please post the output of the bootstrapper. And perhaps add `set -x` to the top of `zsh/bootstrap` before running it.

**Comment by agross** [comment]
Hi,

Sorry for the late reply, but after you edited the OP I didn't receive a notification about that.

I upgraded my Ubuntu VM to 18.10 today and created a new user to test the bootstrapper. It went smoothly. The section after git is gpg which only creates a symlink on Ubuntu, so the error must happen during the git bootstrapper.

The relevant lines are:

```
  [ INFO ] Running /home/test/.dotfiles/git/bootstrap
  [  OK  ] Linked /home/test/.dotfiles/git/gitconfig to /home/test/.gitconfig
  [  OK  ] Linked /home/test/.dotfiles/git/gitconfig.training to /home/test/.gitconfig.training
  [  OK  ] Linked /home/test/.dotfiles/git/git-wtfrc to /home/test/.git-wtfrc
  [  OK  ] Linked /home/test/.dotfiles/git/platform-specific/_/credential-helper.cache.config to /home/test/.git-config/credential-helper.config
  [ INFO ] Running /home/test/.dotfiles/gpg/bootstrap
```

Please post your output here so we can isolate further. I'm going to close this issue until then.
